/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FilmeTableModel;
import controller.ItemController;
import controller.ItemTableModel;
import controller.LivroTableModel;
import controller.RevistaTableModel;
import controller.SoftwareTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import sun.awt.SunToolkit;

/**
 *
 * @author charleshenriqueportoferreira
 */
public class FormBase extends javax.swing.JFrame {

   
    public FormBase() {
        initComponents();        
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSelecaoItem = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuItemUsuario = new javax.swing.JMenuItem();
        menuItemLivro = new javax.swing.JMenuItem();
        menuItemFilme = new javax.swing.JMenuItem();
        menuItemRevista = new javax.swing.JMenuItem();
        menuItemSoftware = new javax.swing.JMenuItem();
        menuItemPrateleira = new javax.swing.JMenuItem();
        menuRenovar = new javax.swing.JMenu();
        menuEmprestimo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastrar.setText("Cadastro");

        menuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuItemUsuario.setText("Usuário");
        menuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemUsuario);

        menuItemLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuItemLivro.setText("Livro");
        menuItemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLivroActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemLivro);

        menuItemFilme.setText("Filme");
        menuItemFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFilmeActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemFilme);

        menuItemRevista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRevista.setText("Revista");
        menuItemRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRevistaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemRevista);

        menuItemSoftware.setText("Software");
        menuItemSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSoftwareActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemSoftware);

        menuItemPrateleira.setText("Prateleira");
        menuItemPrateleira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrateleiraActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemPrateleira);

        jMenuBar1.add(menuCadastrar);

        menuRenovar.setText("Renovacao");
        jMenuBar1.add(menuRenovar);

        menuEmprestimo.setText("Emprestimo");
        jMenuBar1.add(menuEmprestimo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuarioActionPerformed
       this.setVisible(false);
        new CadastroUsuario().setVisible(true);  
        
    }//GEN-LAST:event_menuItemUsuarioActionPerformed

    private void menuItemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLivroActionPerformed
        this.setVisible(false);
        new CadastroLivro().setVisible(true);
             
    }//GEN-LAST:event_menuItemLivroActionPerformed

    private void menuItemRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRevistaActionPerformed
            this.setVisible(false);
            new CadastroRevista().setVisible(true);
    }//GEN-LAST:event_menuItemRevistaActionPerformed

    private void menuItemFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFilmeActionPerformed
        this.setVisible(false);
        new CadastroFilme().setVisible(true);
    }//GEN-LAST:event_menuItemFilmeActionPerformed

    private void menuItemSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSoftwareActionPerformed
        this.setVisible(false);
        new CadastroSoftware().setVisible(true);
    }//GEN-LAST:event_menuItemSoftwareActionPerformed

    private void menuItemPrateleiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrateleiraActionPerformed
       this.setVisible(false);
       new CadastraPrateleira().setVisible(true);
    }//GEN-LAST:event_menuItemPrateleiraActionPerformed

    
    public int getNumeroSemMascara(String valor){
        valor = valor.replaceAll("\\.", "");
        valor = valor.replaceAll("-", "");
        
        return Integer.parseInt(valor);
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSelecaoItem;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuEmprestimo;
    private javax.swing.JMenuItem menuItemFilme;
    private javax.swing.JMenuItem menuItemLivro;
    private javax.swing.JMenuItem menuItemPrateleira;
    private javax.swing.JMenuItem menuItemRevista;
    private javax.swing.JMenuItem menuItemSoftware;
    private javax.swing.JMenuItem menuItemUsuario;
    private javax.swing.JMenu menuRenovar;
    // End of variables declaration//GEN-END:variables
}
