/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FilmeTableModel;
import controller.ItemController;
import controller.ItemTableModel;
import controller.LivroTableModel;
import controller.ReservaTableModel;
import controller.RevistaTableModel;
import controller.SoftwareTableModel;
import facade.ReservaFacade;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import model.Biblioteca;
import model.Item;
import model.Reserva;
import model.Usuario;

/**
 *
 * @author charleshenriqueportoferreira
 */
public class ListaReservas extends javax.swing.JFrame {

    Usuario usuario;
    ItemTableModel itemModelo;
    LivroTableModel modeloLivro;
    RevistaTableModel modeloRevista;
    FilmeTableModel modeloFilme;
    SoftwareTableModel modeloSoftware;
    ReservaTableModel reservaModel;
    JMenuItem menuItemMenu;

    /**
     * Creates new form ListaReservas
     *
     * @param usuario
     * @param item
     */
    public ListaReservas(final Usuario usuario, Item item) {
        this.usuario = usuario;
        initComponents();
        itemModelo = new ItemTableModel();
        modeloLivro = new LivroTableModel();
        modeloRevista = new RevistaTableModel();
        modeloFilme = new FilmeTableModel();
        modeloSoftware = new SoftwareTableModel();
        reservaModel = new ReservaTableModel();
        buscarReservas(item);
        tblBusca.setModel(modeloLivro);
        setLocationRelativeTo(null);
        lblTipoUsuario.setText(usuario.getCategoria().getTipo() + "(a)");
        lblNomeUsuarioLogado.setText(usuario.getNome());
        menuItemMenu = new JMenuItem("Menu", KeyEvent.VK_M);
        menuMenu.add(menuItemMenu);
        menuItemMenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new Menu(usuario).setVisible(true);
                dispose();
            }

        });
    }

    public ListaReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblListaReservas = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNomeUsuarioLogado = new javax.swing.JLabel();
        lblLogado = new javax.swing.JLabel();
        btnLogoff = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        lblTituloItem = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        rdLivro = new javax.swing.JRadioButton();
        rdRevista = new javax.swing.JRadioButton();
        rdFilme = new javax.swing.JRadioButton();
        rdSoftware = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusca = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnReservar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblListaReservas.setFont(new java.awt.Font("Lucida Grande", 3, 25)); // NOI18N
        lblListaReservas.setText("Lista de Reservas");

        lblTipoUsuario.setForeground(new java.awt.Color(0, 0, 255));
        lblTipoUsuario.setText("aaaa");

        lblNomeUsuarioLogado.setForeground(new java.awt.Color(0, 0, 255));
        lblNomeUsuarioLogado.setText("jLabel6");

        lblLogado.setForeground(new java.awt.Color(0, 0, 255));
        lblLogado.setText("logado(a)");

        btnLogoff.setText("logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblListaReservas)
                .addGap(108, 108, 108)
                .addComponent(lblTipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogoff)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogado)
                            .addComponent(lblNomeUsuarioLogado)
                            .addComponent(lblTipoUsuario)
                            .addComponent(btnLogoff)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblListaReservas)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReservas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloItem.setText("Nome do Item:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        rdLivro.setSelected(true);
        rdLivro.setText("Livro");
        rdLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLivroActionPerformed(evt);
            }
        });

        rdRevista.setText("Revista");
        rdRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRevistaActionPerformed(evt);
            }
        });

        rdFilme.setText("Filme");
        rdFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFilmeActionPerformed(evt);
            }
        });

        rdSoftware.setText("Software");
        rdSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSoftwareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(rdLivro)
                .addGap(18, 18, 18)
                .addComponent(rdRevista)
                .addGap(18, 18, 18)
                .addComponent(rdFilme)
                .addGap(28, 28, 28)
                .addComponent(rdSoftware)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloItem)
                .addGap(29, 29, 29)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(266, 266, 266))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloItem)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdLivro)
                    .addComponent(rdRevista)
                    .addComponent(rdFilme)
                    .addComponent(rdSoftware))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusca);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(btnReservar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnReservar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        menuMenu.setText("Menu");
        jMenuBar1.add(menuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        this.usuario = null;
        Biblioteca.abrirLogin();
        this.dispose();
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void rdLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLivroActionPerformed
        tblBusca.setModel(modeloLivro);
    }//GEN-LAST:event_rdLivroActionPerformed

    private void rdRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRevistaActionPerformed
        tblBusca.setModel(modeloRevista);
    }//GEN-LAST:event_rdRevistaActionPerformed

    private void rdFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFilmeActionPerformed
        tblBusca.setModel(modeloFilme);
    }//GEN-LAST:event_rdFilmeActionPerformed

    private void rdSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSoftwareActionPerformed
        tblBusca.setModel(modeloSoftware);
    }//GEN-LAST:event_rdSoftwareActionPerformed

    private void tblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMouseClicked
        
    }//GEN-LAST:event_tblReservasMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ItemController ic = new ItemController();

        if (rdLivro.isSelected()) {
            modeloLivro.limpar();
            modeloLivro.addListaDeLivro(ic.livroFacade.findAllWithValue("titulo", txtTitulo.getText()));
        }
        if (rdRevista.isSelected()) {
            modeloRevista.limpar();
            modeloRevista.addListaDeRvista(ic.revistaFacade.findAllWithValue("titulo", txtTitulo.getText()));
        }
        if (rdFilme.isSelected()) {
            modeloFilme.limpar();
            modeloFilme.addListaDeFilme(ic.filmeFacade.findAllWithValue("titulo", txtTitulo.getText()));
        }
        if (rdSoftware.isSelected()) {
            modeloSoftware.limpar();
            modeloSoftware.addListaDeSoftware(ic.softwareFacade.findAllWithValue("titulo", txtTitulo.getText()));
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        Reserva reserva = new Reserva();
        int row = tblBusca.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um item na tabela para reservar");
            return;
        }
        if (rdLivro.isSelected()) {
            if (possuiExemplarDiponivel(modeloLivro.getLivro(row))) {
                JOptionPane.showMessageDialog(rootPane, "Este Item possui exemplares disponíveis para emprestimo");
                return;
            }
            reserva.setItem(modeloLivro.getLivro(row));
        }
        if (rdRevista.isSelected()) {
            if (possuiExemplarDiponivel(modeloRevista.getRevista(row))) {
                JOptionPane.showMessageDialog(rootPane, "Este Item possui exemplares disponíveis para emprestimo");
                return;
            }
            reserva.setItem(modeloRevista.getRevista(row));
        }
        if (rdFilme.isSelected()) {
            if (possuiExemplarDiponivel(modeloFilme.getFilme(row))) {
                JOptionPane.showMessageDialog(rootPane, "Este Item possui exemplares disponíveis para emprestimo");
                return;
            }
            reserva.setItem(modeloFilme.getFilme(row));
        }
        if (rdSoftware.isSelected()) {
            if (possuiExemplarDiponivel(modeloSoftware.getSoftware(row))) {
                JOptionPane.showMessageDialog(rootPane, "Este Item possui exemplares disponíveis para emprestimo");
                return;
            }
            reserva.setItem(modeloSoftware.getSoftware(row));
        }

        reserva.setUsuario(usuario);
        reserva.setDataReserva(Date.from(Instant.now()));
        ReservaFacade rf = new ReservaFacade();
        rf.edit(reserva);
        JOptionPane.showMessageDialog(rootPane, "Item reservado");
        buscarReservas(reserva.getItem());


    }//GEN-LAST:event_btnReservarActionPerformed

    private void tblBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscaMouseClicked
        
        if (evt.getClickCount() == 1) {
            ReservaFacade rf = new ReservaFacade();
            int row = tblBusca.getSelectedRow();
            if (rdLivro.isSelected()) {
                List<Reserva> reservas = rf.findAllWithItem( modeloLivro.getLivro(row).getId().toString(),"");
                reservaModel.limpar();
                reservaModel.addListaDeReserva(reservas);
            }
            if (rdRevista.isSelected()) {
                List<Reserva> reservas = rf.findAllWithItem(modeloRevista.getRevista(row).getId().toString(),"");
                reservaModel.limpar();
                reservaModel.addListaDeReserva(reservas);
            }
            if (rdFilme.isSelected()) {
                List<Reserva> reservas = rf.findAllWithItem( modeloFilme.getFilme(row).getId().toString(),"");
                reservaModel.limpar();
                reservaModel.addListaDeReserva(reservas);
            }
            if (rdSoftware.isSelected()) {
                List<Reserva> reservas = rf.findAllWithItem( modeloSoftware.getSoftware(row).getId().toString(),"");
                reservaModel.limpar();
                reservaModel.addListaDeReserva(reservas);
            }

        }
        
    }//GEN-LAST:event_tblBuscaMouseClicked

    private boolean possuiExemplarDiponivel(Item item) {
        return item.getQtdeExemplaresDisponiveis() != 0;
    }

    private void buscarReservas(Item item) {
        ReservaFacade rf = new ReservaFacade();
        List<Reserva> reservas = rf.findAllWithItem(item.getId().toString(), "");
        reservaModel.limpar();
        reservaModel.addListaDeReserva(reservas);
        tblReservas.setModel(reservaModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnReservar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblListaReservas;
    private javax.swing.JLabel lblLogado;
    private javax.swing.JLabel lblNomeUsuarioLogado;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblTituloItem;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JRadioButton rdFilme;
    private javax.swing.JRadioButton rdLivro;
    private javax.swing.JRadioButton rdRevista;
    private javax.swing.JRadioButton rdSoftware;
    private javax.swing.JTable tblBusca;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
